apiVersion: v1
kind: Namespace
metadata: { name: amazon-cloudwatch }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: REPLACE_ME_EKS_CLUSTER_NAME
  logs.region: REPLACE_ME_AWS_REGION
  http.server: "On"
  http.port: "2020"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: amazon-cloudwatch
spec:
  selector: { matchLabels: { k8s-app: fluent-bit } }
  template:
    metadata: { labels: { k8s-app: fluent-bit } }
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
          envFrom: [{ configMapRef: { name: fluent-bit-cluster-info } }]
          resources:
            limits: { memory: "200Mi" }
            requests: { cpu: "100m", memory: "100Mi" }
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: varlog
          hostPath: { path: /var/log }
        - name: varlibdockercontainers
          hostPath: { path: /var/lib/docker/containers }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: amazon-cloudwatch
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_ME_IRSA_FOR_CLOUDWATCH # optional
